# Generated by Django 4.2.4 on 2023-08-20 10:43

from django.db import migrations
from truecaller_backend.helper import generate_random_string


# Inserting the default users.
def insert_users(apps, schema_editor):
    User = apps.get_model("truecaller_backend", "User")
    User.objects.create(
        user_id="gvdhbjnghdjnsbdahjsdgjhy65r6787fhvgbhgvcy5645tfgsd",
        name="Nakul Gupta",
        country_code="+91",
        phone_number="8802631740",
        email="nakulgupta1042@gmail.com",
        password="$2a$12$IaQ1oYXZdmPcz5eZrUFYqeYIDT3JJ9JO5B9HnDW2CvQ4W3NUHbnoe",
    )
    User.objects.create(
        user_id="njbhjy8tr7ytrfdcvbhgfdr657646578iyugfhuyyt54556734",
        name="TrueCaller Team",
        country_code="+91",
        phone_number="8888888888",
        email="truecaller_backend@gmail.com",
        password="$2a$12$xwbwN9IJ8GuXGR/311Nq3eAeVlwxkvz5BURaMPad4OjWVZ/mQOh6y",
    )
    User.objects.create(
        user_id="bhkscnkvgusdhuiygushbjdsgd762374yighjwfdsgdsdf534w",
        name="TrueCaller Team 1",
        country_code="+91",
        phone_number="7777777777",
        password="$2a$12$I1apu/MZoZR3NQP.9olEzO6HkREVMYPq9DCP0Ej9pBC1ziOB/h1j2",
    )


# Inserting Demo Contacts linked with the user.
def insert_contacts(apps, schema_editor):
    Contacts = apps.get_model("truecaller_backend", "Contacts")
    for i in range(1, 101):
        contact_id = f"{generate_random_string(50)}"
        # If i is even then contact is imported by "Nakul Gupta"
        # or if i is divisble by 3 then contact is imported by "TrueCaller Team"
        # else contact is imported by "TrueCaller Team 1"
        user_id_imported_contacts = (
            "gvdhbjnghdjnsbdahjsdgjhy65r6787fhvgbhgvcy5645tfgsd"
            if i % 2 == 0
            else (
                "njbhjy8tr7ytrfdcvbhgfdr657646578iyugfhuyyt54556734"
                if i % 3 == 0
                else "bhkscnkvgusdhuiygushbjdsgd762374yighjwfdsgdsdf534w"
            )
        )
        # If i is greater than 50 then add IH_ suffix to the name.
        # This will help in arranging the search result by str starts
        # with name in the first then if the string containg in middle.
        name = ("IH_" if i > 50 else "") + f"User Name {i%10}"
        country_code = "+91"
        phone_number = f"952476574{i%10}"
        Contacts.objects.create(
            contact_id=contact_id,
            user_id_imported_contacts=user_id_imported_contacts,
            name=name,
            country_code=country_code,
            phone_number=phone_number,
        )
    # Added These Contact that will help in getting the email if search by
    # the user that is in the searched person contact list.
    Contacts.objects.create(
        contact_id=generate_random_string(50),
        user_id_imported_contacts="njbhjy8tr7ytrfdcvbhgfdr657646578iyugfhuyyt54556734",
        name="Nakul Gupta",
        country_code="+91",
        phone_number="8802631740",
    )
    Contacts.objects.create(
        contact_id="5PMkdCInUk7vBUb1biOa4OHpagS7ZjeDK2Nx2kzHJkMECsZQZ_",
        user_id_imported_contacts="gvdhbjnghdjnsbdahjsdgjhy65r6787fhvgbhgvcy5645tfgsd",
        name="TrueCaller Team",
        country_code="+91",
        phone_number="8888888888",
    )
    Contacts.objects.create(
        contact_id="ewef3CInUk7vBUb1biOa4OHpagS7ZjeDK2Nx2kzHJkMECsssf_",
        name="TrueCaller Team 2",
        country_code="+91",
        phone_number="9435346533",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("truecaller_backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_users),
        migrations.RunPython(insert_contacts),
    ]
